platform :ios, '9.0'
use_frameworks!

target 'OGHakuba_Example' do
  pod 'OGHakuba', :path => '../'

  pod 'SwiftLint', '0.21.0'

  target 'OGHakuba_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0', :inhibit_warnings => true
    pod 'Nimble', '~> 5.1.1', :inhibit_warnings => true
    pod 'FBSnapshotTestCase', :inhibit_warnings => true
    pod 'Nimble-Snapshots', :inhibit_warnings => true
  end
end
